#!/bin/bash
source ~/scraperTests/venv_scrapers/bin/activate
python scraper_24ur.py
python scraper_agen_rs.py
python scraper_amazon_eu.py
python scraper_dol_muzej.py
python scraper_e3.py
python scraper_elektroPrimorska.py
python scraper_essGov.py
python scraper_golea.py
python scraper_interreg.py
python scraper_iun.py
python scraper_ljnovice.py
python scraper_maribor24.py
python scraper_mddsz.py
python scraper_mizs_gov.py
python scraper_mizs_gov.py
python scraper_mop_gov.py
python scraper_nascas.py
python scraper_nasstik.py
python scraper_novaGorica.py
python scraper_obcinaIdrija.py
python scraper_obcinaLjubljana.py
python scraper_obcinaLjubljana2.py
python scraper_obcinaMaribor.py
python scraper_obcinaTolmin.py
python scraper_prc.py
python scraper_primorske.py
python scraper_primorskiVal.py
python scraper_regionalObala.py
python scraper_sazu.py
python scraper_siol.py
python scraper_turisticnaZveza.py
python scraper_velenjcan.py
python scraper_zdruzenje_obcin.py
python scraper_zrcSazu.py
python scraper_zvdks.py
deactivate
